version: '3.1'

services:

  postgres:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: appuser
      POSTGRES_DB: timeflix
    expose: 
      - 5432
    ports:
      - 5432:5432
    networks:
      - my-network
  api:
    image: dinkod/timeflix_api:latest
    container_name: api
    ports: 
      - 5001:80
    networks:
      - my-network
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: appuser
      POSTGRES_DB: timeflix
    depends_on: 
      - postgres
  client:
    image: dinkod/timeflix_client:latest
    container_name: client
    expose: 
      - 80
      - 443
    ports: 
      - 4000:80
    networks: 
      - my-network
networks:
  my-network:
    external: true
